// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package database

import (
	"golang-rest-api-clean-architecture/pkg/external-services/database/repositories"
	"sync"
)

// Ensure, that DbClientMock does implement DbClient.
// If this is not the case, regenerate this file with moq.
var _ DbClient = &DbClientMock{}

// DbClientMock is a mock implementation of DbClient.
//
// 	func TestSomethingThatUsesDbClient(t *testing.T) {
//
// 		// make and configure a mocked DbClient
// 		mockedDbClient := &DbClientMock{
// 			GetCompanyRepositoryFunc: func() repositories.CompanyRepository {
// 				panic("mock out the GetCompanyRepository method")
// 			},
// 		}
//
// 		// use mockedDbClient in code that requires DbClient
// 		// and then make assertions.
//
// 	}
type DbClientMock struct {
	// GetCompanyRepositoryFunc mocks the GetCompanyRepository method.
	GetCompanyRepositoryFunc func() repositories.CompanyRepository

	// calls tracks calls to the methods.
	calls struct {
		// GetCompanyRepository holds details about calls to the GetCompanyRepository method.
		GetCompanyRepository []struct {
		}
	}
	lockGetCompanyRepository sync.RWMutex
}

// GetCompanyRepository calls GetCompanyRepositoryFunc.
func (mock *DbClientMock) GetCompanyRepository() repositories.CompanyRepository {
	if mock.GetCompanyRepositoryFunc == nil {
		panic("DbClientMock.GetCompanyRepositoryFunc: method is nil but DbClient.GetCompanyRepository was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCompanyRepository.Lock()
	mock.calls.GetCompanyRepository = append(mock.calls.GetCompanyRepository, callInfo)
	mock.lockGetCompanyRepository.Unlock()
	return mock.GetCompanyRepositoryFunc()
}

// GetCompanyRepositoryCalls gets all the calls that were made to GetCompanyRepository.
// Check the length with:
//     len(mockedDbClient.GetCompanyRepositoryCalls())
func (mock *DbClientMock) GetCompanyRepositoryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCompanyRepository.RLock()
	calls = mock.calls.GetCompanyRepository
	mock.lockGetCompanyRepository.RUnlock()
	return calls
}
